"""Constants for BSEED ZHA Switches."""

DOMAIN = "bseed_zha_switches"

BSEED_MANUFACTURER = "BSEED"
RAW_MODEL = "TS0726"

MODEL_1_GANG = "EC-GL86ZPCS11"
MODEL_2_GANG = "EC-GL86ZPCS21"

MANUFACTURER_1_GANG = "_TZ3002_jn2x20tg"
MANUFACTURER_2_GANG = "_TZ3002_zjuvw9zf"

ZHA_DOMAIN = "zha"

CLUSTER_ON_OFF = 0x0006
CLUSTER_TUYA_OPTIONS = 0xE001

ATTR_BACKLIGHT_MODE = 0x5000
ATTR_INDICATOR_MODE = 0x8001
ATTR_POWER_ON_BEHAVIOR = 0xD010
ATTR_SWITCH_MODE = 0xD020

OPTION_BACKLIGHT = {"off": 0, "on": 1}
OPTION_INDICATOR = {"none": 0, "relay": 1, "pos": 2}
OPTION_POWER_ON = {"off": 0, "on": 1, "previous": 2}
OPTION_SWITCH_MODE = {"switch": 0, "scene": 1}
